apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruby-deployment
  labels:
    app: ruby
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ruby
  template:
    metadata:
      labels:
        app: ruby
    spec:
      containers:
      - name: ruby
        image: ruby-truecaller:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /blog/config/cequel.yml
          name: cequel
          subPath: cequel.yml
      volumes:       
      - name: cequel
        configMap:
          name: cequel-cm
          items:
            - key: cequel.yaml
              path: cequel.yml